@port = 8080
@baseUrl = http://localhost:{{port}}/api

### * Create System Log
POST {{baseUrl}}/system-logs
Content-Type: application/json

{
  "action": "Login",
  "module": "Authentication",
  "user": "67e2aed0fce7da39a1472d00",
  "details": "User logged in successfully"
}

### * Get All System Logs
GET {{baseUrl}}/system-logs

### * Get System Log by ID
GET {{baseUrl}}/system-logs/67e2bb5e38c5fd2325315cfc

### * Update System Log by ID
PUT {{baseUrl}}/system-logs/67e2bb5e38c5fd2325315cfc
Content-Type: application/json

{
  "details": "User login attempt failed"
}

### * Delete System Log by ID
DELETE {{baseUrl}}/system-logs/65f6e4d1c2a5f5d6f12ab346

### * Delete All System Logs
DELETE {{baseUrl}}/system-logs/all
